import { Word } from '@haikupedias/core/types';

/**
 * Word Dataset B — Dynamic & Urban
 *
 * This dataset focuses on movement, energy, and contemporary urban life.
 * Provides contrast to the contemplative quality of Dataset A.
 */
export const WORD_SET_B: Word[] = [
  // Nouns - Major tonality
  { id: 'b-n-01', label: 'city', type: 'noun', tonalityGroup: 'major' },
  { id: 'b-n-02', label: 'street', type: 'noun', tonalityGroup: 'major' },
  { id: 'b-n-03', label: 'pulse', type: 'noun', tonalityGroup: 'major' },
  { id: 'b-n-04', label: 'spark', type: 'noun', tonalityGroup: 'major' },
  { id: 'b-n-05', label: 'rhythm', type: 'noun', tonalityGroup: 'major' },
  { id: 'b-n-06', label: 'moment', type: 'noun', tonalityGroup: 'major' },
  { id: 'b-n-07', label: 'dance', type: 'noun', tonalityGroup: 'major' },
  { id: 'b-n-08', label: 'fire', type: 'noun', tonalityGroup: 'major' },
  { id: 'b-n-09', label: 'wave', type: 'noun', tonalityGroup: 'major' },
  { id: 'b-n-10', label: 'step', type: 'noun', tonalityGroup: 'major' },
  { id: 'b-n-11', label: 'voice', type: 'noun', tonalityGroup: 'major' },
  { id: 'b-n-12', label: 'morning', type: 'noun', tonalityGroup: 'major' },
  { id: 'b-n-25', label: 'signal', type: 'noun', tonalityGroup: 'major' },
  { id: 'b-n-26', label: 'avenue', type: 'noun', tonalityGroup: 'major' },
  { id: 'b-n-27', label: 'engine', type: 'noun', tonalityGroup: 'major' },
  { id: 'b-n-28', label: 'neon', type: 'noun', tonalityGroup: 'major' },
  { id: 'b-n-29', label: 'tempo', type: 'noun', tonalityGroup: 'major' },
  { id: 'b-n-30', label: 'bridge', type: 'noun', tonalityGroup: 'major' },
  { id: 'b-n-31', label: 'station', type: 'noun', tonalityGroup: 'major' },
  { id: 'b-n-32', label: 'plaza', type: 'noun', tonalityGroup: 'major' },
  { id: 'b-n-33', label: 'chorus', type: 'noun', tonalityGroup: 'major' },
  { id: 'b-n-34', label: 'sunbeam', type: 'noun', tonalityGroup: 'major' },
  { id: 'b-n-35', label: 'crosswalk', type: 'noun', tonalityGroup: 'major' },
  { id: 'b-n-36', label: 'rooftop', type: 'noun', tonalityGroup: 'major' },

  // Nouns - Minor tonality
  { id: 'b-n-13', label: 'corner', type: 'noun', tonalityGroup: 'minor' },
  { id: 'b-n-14', label: 'distance', type: 'noun', tonalityGroup: 'minor' },
  { id: 'b-n-15', label: 'absence', type: 'noun', tonalityGroup: 'minor' },
  { id: 'b-n-16', label: 'threshold', type: 'noun', tonalityGroup: 'minor' },
  { id: 'b-n-17', label: 'fragment', type: 'noun', tonalityGroup: 'minor' },
  { id: 'b-n-18', label: 'maze', type: 'noun', tonalityGroup: 'minor' },
  { id: 'b-n-19', label: 'crowd', type: 'noun', tonalityGroup: 'minor' },
  { id: 'b-n-20', label: 'glass', type: 'noun', tonalityGroup: 'minor' },
  { id: 'b-n-21', label: 'steel', type: 'noun', tonalityGroup: 'minor' },
  { id: 'b-n-22', label: 'concrete', type: 'noun', tonalityGroup: 'minor' },
  { id: 'b-n-23', label: 'stranger', type: 'noun', tonalityGroup: 'minor' },
  { id: 'b-n-24', label: 'window', type: 'noun', tonalityGroup: 'minor' },
  { id: 'b-n-37', label: 'alley', type: 'noun', tonalityGroup: 'minor' },
  { id: 'b-n-38', label: 'subway', type: 'noun', tonalityGroup: 'minor' },
  { id: 'b-n-39', label: 'smog', type: 'noun', tonalityGroup: 'minor' },
  { id: 'b-n-40', label: 'vacancy', type: 'noun', tonalityGroup: 'minor' },
  { id: 'b-n-41', label: 'static', type: 'noun', tonalityGroup: 'minor' },
  { id: 'b-n-42', label: 'sirens', type: 'noun', tonalityGroup: 'minor' },
  { id: 'b-n-43', label: 'underpass', type: 'noun', tonalityGroup: 'minor' },
  { id: 'b-n-44', label: 'detour', type: 'noun', tonalityGroup: 'minor' },
  { id: 'b-n-45', label: 'flicker', type: 'noun', tonalityGroup: 'minor' },
  { id: 'b-n-46', label: 'rainfall', type: 'noun', tonalityGroup: 'minor' },
  { id: 'b-n-47', label: 'midnight', type: 'noun', tonalityGroup: 'minor' },
  { id: 'b-n-48', label: 'antenna', type: 'noun', tonalityGroup: 'minor' },

  // Adjectives - Major tonality
  { id: 'b-adj-01', label: 'bright', type: 'adjective', tonalityGroup: 'major' },
  { id: 'b-adj-02', label: 'sharp', type: 'adjective', tonalityGroup: 'major' },
  { id: 'b-adj-03', label: 'quick', type: 'adjective', tonalityGroup: 'major' },
  { id: 'b-adj-04', label: 'vivid', type: 'adjective', tonalityGroup: 'major' },
  { id: 'b-adj-05', label: 'alive', type: 'adjective', tonalityGroup: 'major' },
  { id: 'b-adj-06', label: 'electric', type: 'adjective', tonalityGroup: 'major' },
  { id: 'b-adj-07', label: 'fierce', type: 'adjective', tonalityGroup: 'major' },
  { id: 'b-adj-08', label: 'bold', type: 'adjective', tonalityGroup: 'major' },
  { id: 'b-adj-09', label: 'sudden', type: 'adjective', tonalityGroup: 'major' },
  { id: 'b-adj-10', label: 'restless', type: 'adjective', tonalityGroup: 'major' },
  { id: 'b-adj-11', label: 'urgent', type: 'adjective', tonalityGroup: 'major' },
  { id: 'b-adj-12', label: 'burning', type: 'adjective', tonalityGroup: 'major' },
  { id: 'b-adj-25', label: 'kinetic', type: 'adjective', tonalityGroup: 'major' },
  { id: 'b-adj-26', label: 'resonant', type: 'adjective', tonalityGroup: 'major' },
  { id: 'b-adj-27', label: 'brisk', type: 'adjective', tonalityGroup: 'major' },
  { id: 'b-adj-28', label: 'glittering', type: 'adjective', tonalityGroup: 'major' },
  { id: 'b-adj-29', label: 'fearless', type: 'adjective', tonalityGroup: 'major' },
  { id: 'b-adj-30', label: 'crisp', type: 'adjective', tonalityGroup: 'major' },
  { id: 'b-adj-31', label: 'fluent', type: 'adjective', tonalityGroup: 'major' },
  { id: 'b-adj-32', label: 'sunny', type: 'adjective', tonalityGroup: 'major' },
  { id: 'b-adj-33', label: 'spirited', type: 'adjective', tonalityGroup: 'major' },
  { id: 'b-adj-34', label: 'rapid', type: 'adjective', tonalityGroup: 'major' },
  { id: 'b-adj-35', label: 'charged', type: 'adjective', tonalityGroup: 'major' },
  { id: 'b-adj-36', label: 'buoyant', type: 'adjective', tonalityGroup: 'major' },

  // Adjectives - Minor tonality
  { id: 'b-adj-13', label: 'fractured', type: 'adjective', tonalityGroup: 'minor' },
  { id: 'b-adj-14', label: 'harsh', type: 'adjective', tonalityGroup: 'minor' },
  { id: 'b-adj-15', label: 'broken', type: 'adjective', tonalityGroup: 'minor' },
  { id: 'b-adj-16', label: 'distant', type: 'adjective', tonalityGroup: 'minor' },
  { id: 'b-adj-17', label: 'empty', type: 'adjective', tonalityGroup: 'minor' },
  { id: 'b-adj-18', label: 'numb', type: 'adjective', tonalityGroup: 'minor' },
  { id: 'b-adj-19', label: 'heavy', type: 'adjective', tonalityGroup: 'minor' },
  { id: 'b-adj-20', label: 'dark', type: 'adjective', tonalityGroup: 'minor' },
  { id: 'b-adj-21', label: 'endless', type: 'adjective', tonalityGroup: 'minor' },
  { id: 'b-adj-22', label: 'blurred', type: 'adjective', tonalityGroup: 'minor' },
  { id: 'b-adj-23', label: 'worn', type: 'adjective', tonalityGroup: 'minor' },
  { id: 'b-adj-24', label: 'trapped', type: 'adjective', tonalityGroup: 'minor' },
  { id: 'b-adj-37', label: 'brittle', type: 'adjective', tonalityGroup: 'minor' },
  { id: 'b-adj-38', label: 'vacant', type: 'adjective', tonalityGroup: 'minor' },
  { id: 'b-adj-39', label: 'faded', type: 'adjective', tonalityGroup: 'minor' },
  { id: 'b-adj-40', label: 'ashen', type: 'adjective', tonalityGroup: 'minor' },
  { id: 'b-adj-41', label: 'sleepless', type: 'adjective', tonalityGroup: 'minor' },
  { id: 'b-adj-42', label: 'hollow', type: 'adjective', tonalityGroup: 'minor' },
  { id: 'b-adj-43', label: 'noisy', type: 'adjective', tonalityGroup: 'minor' },
  { id: 'b-adj-44', label: 'uneven', type: 'adjective', tonalityGroup: 'minor' },
  { id: 'b-adj-45', label: 'overcast', type: 'adjective', tonalityGroup: 'minor' },
  { id: 'b-adj-46', label: 'stray', type: 'adjective', tonalityGroup: 'minor' },
  { id: 'b-adj-47', label: 'torn', type: 'adjective', tonalityGroup: 'minor' },
  { id: 'b-adj-48', label: 'stalled', type: 'adjective', tonalityGroup: 'minor' },

  // Verbs - Major tonality
  { id: 'b-v-01', label: 'rush', type: 'verb', tonalityGroup: 'major' },
  { id: 'b-v-02', label: 'ignite', type: 'verb', tonalityGroup: 'major' },
  { id: 'b-v-03', label: 'leap', type: 'verb', tonalityGroup: 'major' },
  { id: 'b-v-04', label: 'burst', type: 'verb', tonalityGroup: 'major' },
  { id: 'b-v-05', label: 'pulse', type: 'verb', tonalityGroup: 'major' },
  { id: 'b-v-06', label: 'race', type: 'verb', tonalityGroup: 'major' },
  { id: 'b-v-07', label: 'flash', type: 'verb', tonalityGroup: 'major' },
  { id: 'b-v-08', label: 'spin', type: 'verb', tonalityGroup: 'major' },
  { id: 'b-v-09', label: 'soar', type: 'verb', tonalityGroup: 'major' },
  { id: 'b-v-10', label: 'strike', type: 'verb', tonalityGroup: 'major' },
  { id: 'b-v-11', label: 'break', type: 'verb', tonalityGroup: 'major' },
  { id: 'b-v-12', label: 'shake', type: 'verb', tonalityGroup: 'major' },
  { id: 'b-v-25', label: 'launch', type: 'verb', tonalityGroup: 'major' },
  { id: 'b-v-26', label: 'accelerate', type: 'verb', tonalityGroup: 'major' },
  { id: 'b-v-27', label: 'sparkle', type: 'verb', tonalityGroup: 'major' },
  { id: 'b-v-28', label: 'surge', type: 'verb', tonalityGroup: 'major' },
  { id: 'b-v-29', label: 'charge', type: 'verb', tonalityGroup: 'major' },
  { id: 'b-v-30', label: 'climb', type: 'verb', tonalityGroup: 'major' },
  { id: 'b-v-31', label: 'expand', type: 'verb', tonalityGroup: 'major' },
  { id: 'b-v-32', label: 'thread', type: 'verb', tonalityGroup: 'major' },
  { id: 'b-v-33', label: 'signal', type: 'verb', tonalityGroup: 'major' },
  { id: 'b-v-34', label: 'glide', type: 'verb', tonalityGroup: 'major' },
  { id: 'b-v-35', label: 'unite', type: 'verb', tonalityGroup: 'major' },
  { id: 'b-v-36', label: 'lift', type: 'verb', tonalityGroup: 'major' },

  // Verbs - Minor tonality
  { id: 'b-v-13', label: 'collapse', type: 'verb', tonalityGroup: 'minor' },
  { id: 'b-v-14', label: 'scatter', type: 'verb', tonalityGroup: 'minor' },
  { id: 'b-v-15', label: 'shatter', type: 'verb', tonalityGroup: 'minor' },
  { id: 'b-v-16', label: 'wander', type: 'verb', tonalityGroup: 'minor' },
  { id: 'b-v-17', label: 'stare', type: 'verb', tonalityGroup: 'minor' },
  { id: 'b-v-18', label: 'stumble', type: 'verb', tonalityGroup: 'minor' },
  { id: 'b-v-19', label: 'hesitate', type: 'verb', tonalityGroup: 'minor' },
  { id: 'b-v-20', label: 'fracture', type: 'verb', tonalityGroup: 'minor' },
  { id: 'b-v-21', label: 'search', type: 'verb', tonalityGroup: 'minor' },
  { id: 'b-v-22', label: 'blur', type: 'verb', tonalityGroup: 'minor' },
  { id: 'b-v-23', label: 'echo', type: 'verb', tonalityGroup: 'minor' },
  { id: 'b-v-24', label: 'drift', type: 'verb', tonalityGroup: 'minor' },
  { id: 'b-v-37', label: 'stall', type: 'verb', tonalityGroup: 'minor' },
  { id: 'b-v-38', label: 'sink', type: 'verb', tonalityGroup: 'minor' },
  { id: 'b-v-39', label: 'splinter', type: 'verb', tonalityGroup: 'minor' },
  { id: 'b-v-40', label: 'erupt', type: 'verb', tonalityGroup: 'minor' },
  { id: 'b-v-41', label: 'linger', type: 'verb', tonalityGroup: 'minor' },
  { id: 'b-v-42', label: 'disperse', type: 'verb', tonalityGroup: 'minor' },
  { id: 'b-v-43', label: 'falter', type: 'verb', tonalityGroup: 'minor' },
  { id: 'b-v-44', label: 'drain', type: 'verb', tonalityGroup: 'minor' },
  { id: 'b-v-45', label: 'recede', type: 'verb', tonalityGroup: 'minor' },
  { id: 'b-v-46', label: 'drone', type: 'verb', tonalityGroup: 'minor' },
  { id: 'b-v-47', label: 'loiter', type: 'verb', tonalityGroup: 'minor' },
  { id: 'b-v-48', label: 'fade', type: 'verb', tonalityGroup: 'minor' },

  // Adverbs - Major tonality
  { id: 'b-adv-01', label: 'swiftly', type: 'adverb', tonalityGroup: 'major' },
  { id: 'b-adv-02', label: 'fiercely', type: 'adverb', tonalityGroup: 'major' },
  { id: 'b-adv-03', label: 'brightly', type: 'adverb', tonalityGroup: 'major' },
  { id: 'b-adv-04', label: 'sharply', type: 'adverb', tonalityGroup: 'major' },
  { id: 'b-adv-05', label: 'boldly', type: 'adverb', tonalityGroup: 'major' },
  { id: 'b-adv-06', label: 'wildly', type: 'adverb', tonalityGroup: 'major' },
  { id: 'b-adv-13', label: 'clearly', type: 'adverb', tonalityGroup: 'major' },
  { id: 'b-adv-14', label: 'briskly', type: 'adverb', tonalityGroup: 'major' },
  { id: 'b-adv-15', label: 'vividly', type: 'adverb', tonalityGroup: 'major' },
  { id: 'b-adv-16', label: 'openly', type: 'adverb', tonalityGroup: 'major' },
  { id: 'b-adv-17', label: 'loudly', type: 'adverb', tonalityGroup: 'major' },
  { id: 'b-adv-18', label: 'warmly', type: 'adverb', tonalityGroup: 'major' },

  // Adverbs - Minor tonality
  { id: 'b-adv-07', label: 'endlessly', type: 'adverb', tonalityGroup: 'minor' },
  { id: 'b-adv-08', label: 'heavily', type: 'adverb', tonalityGroup: 'minor' },
  { id: 'b-adv-09', label: 'distantly', type: 'adverb', tonalityGroup: 'minor' },
  { id: 'b-adv-10', label: 'numbly', type: 'adverb', tonalityGroup: 'minor' },
  { id: 'b-adv-11', label: 'harshly', type: 'adverb', tonalityGroup: 'minor' },
  { id: 'b-adv-12', label: 'emptily', type: 'adverb', tonalityGroup: 'minor' },
  { id: 'b-adv-19', label: 'faintly', type: 'adverb', tonalityGroup: 'minor' },
  { id: 'b-adv-20', label: 'slowly', type: 'adverb', tonalityGroup: 'minor' },
  { id: 'b-adv-21', label: 'uneasily', type: 'adverb', tonalityGroup: 'minor' },
  { id: 'b-adv-22', label: 'roughly', type: 'adverb', tonalityGroup: 'minor' },
  { id: 'b-adv-23', label: 'blindly', type: 'adverb', tonalityGroup: 'minor' },
  { id: 'b-adv-24', label: 'vacantly', type: 'adverb', tonalityGroup: 'minor' },
];
