import { Word } from '@haikupedias/core/types';

/**
 * Word Dataset A — Contemplative & Natural
 *
 * This dataset focuses on nature, contemplation, and quiet moments.
 * Inspired by the meditative quality of Gymnopédies.
 */
export const WORD_SET_A: Word[] = [
  // Nouns - Major tonality
  { id: 'a-n-01', label: 'cloud', type: 'noun', tonalityGroup: 'major' },
  { id: 'a-n-02', label: 'water', type: 'noun', tonalityGroup: 'major' },
  { id: 'a-n-03', label: 'light', type: 'noun', tonalityGroup: 'major' },
  { id: 'a-n-04', label: 'breeze', type: 'noun', tonalityGroup: 'major' },
  { id: 'a-n-05', label: 'dawn', type: 'noun', tonalityGroup: 'major' },
  { id: 'a-n-06', label: 'garden', type: 'noun', tonalityGroup: 'major' },
  { id: 'a-n-07', label: 'flower', type: 'noun', tonalityGroup: 'major' },
  { id: 'a-n-08', label: 'sky', type: 'noun', tonalityGroup: 'major' },
  { id: 'a-n-09', label: 'stone', type: 'noun', tonalityGroup: 'major' },
  { id: 'a-n-10', label: 'river', type: 'noun', tonalityGroup: 'major' },
  { id: 'a-n-11', label: 'leaf', type: 'noun', tonalityGroup: 'major' },
  { id: 'a-n-12', label: 'moon', type: 'noun', tonalityGroup: 'major' },
  { id: 'a-n-25', label: 'meadow', type: 'noun', tonalityGroup: 'major' },
  { id: 'a-n-26', label: 'harbor', type: 'noun', tonalityGroup: 'major' },
  { id: 'a-n-27', label: 'sunrise', type: 'noun', tonalityGroup: 'major' },
  { id: 'a-n-28', label: 'petal', type: 'noun', tonalityGroup: 'major' },
  { id: 'a-n-29', label: 'path', type: 'noun', tonalityGroup: 'major' },
  { id: 'a-n-30', label: 'grove', type: 'noun', tonalityGroup: 'major' },
  { id: 'a-n-31', label: 'horizon', type: 'noun', tonalityGroup: 'major' },
  { id: 'a-n-32', label: 'valley', type: 'noun', tonalityGroup: 'major' },
  { id: 'a-n-33', label: 'brook', type: 'noun', tonalityGroup: 'major' },
  { id: 'a-n-34', label: 'feather', type: 'noun', tonalityGroup: 'major' },
  { id: 'a-n-35', label: 'blossom', type: 'noun', tonalityGroup: 'major' },
  { id: 'a-n-36', label: 'shore', type: 'noun', tonalityGroup: 'major' },

  // Nouns - Minor tonality
  { id: 'a-n-13', label: 'shadow', type: 'noun', tonalityGroup: 'minor' },
  { id: 'a-n-14', label: 'silence', type: 'noun', tonalityGroup: 'minor' },
  { id: 'a-n-15', label: 'mist', type: 'noun', tonalityGroup: 'minor' },
  { id: 'a-n-16', label: 'evening', type: 'noun', tonalityGroup: 'minor' },
  { id: 'a-n-17', label: 'echo', type: 'noun', tonalityGroup: 'minor' },
  { id: 'a-n-18', label: 'fog', type: 'noun', tonalityGroup: 'minor' },
  { id: 'a-n-19', label: 'rain', type: 'noun', tonalityGroup: 'minor' },
  { id: 'a-n-20', label: 'winter', type: 'noun', tonalityGroup: 'minor' },
  { id: 'a-n-21', label: 'dust', type: 'noun', tonalityGroup: 'minor' },
  { id: 'a-n-22', label: 'memory', type: 'noun', tonalityGroup: 'minor' },
  { id: 'a-n-23', label: 'night', type: 'noun', tonalityGroup: 'minor' },
  { id: 'a-n-24', label: 'wind', type: 'noun', tonalityGroup: 'minor' },
  { id: 'a-n-37', label: 'twilight', type: 'noun', tonalityGroup: 'minor' },
  { id: 'a-n-38', label: 'ember', type: 'noun', tonalityGroup: 'minor' },
  { id: 'a-n-39', label: 'haze', type: 'noun', tonalityGroup: 'minor' },
  { id: 'a-n-40', label: 'stillness', type: 'noun', tonalityGroup: 'minor' },
  { id: 'a-n-41', label: 'hollow', type: 'noun', tonalityGroup: 'minor' },
  { id: 'a-n-42', label: 'frost', type: 'noun', tonalityGroup: 'minor' },
  { id: 'a-n-43', label: 'drizzle', type: 'noun', tonalityGroup: 'minor' },
  { id: 'a-n-44', label: 'ruin', type: 'noun', tonalityGroup: 'minor' },
  { id: 'a-n-45', label: 'midnight', type: 'noun', tonalityGroup: 'minor' },
  { id: 'a-n-46', label: 'ash', type: 'noun', tonalityGroup: 'minor' },
  { id: 'a-n-47', label: 'thicket', type: 'noun', tonalityGroup: 'minor' },
  { id: 'a-n-48', label: 'distance', type: 'noun', tonalityGroup: 'minor' },

  // Adjectives - Major tonality
  { id: 'a-adj-01', label: 'clear', type: 'adjective', tonalityGroup: 'major' },
  { id: 'a-adj-02', label: 'bright', type: 'adjective', tonalityGroup: 'major' },
  { id: 'a-adj-03', label: 'soft', type: 'adjective', tonalityGroup: 'major' },
  { id: 'a-adj-04', label: 'gentle', type: 'adjective', tonalityGroup: 'major' },
  { id: 'a-adj-05', label: 'still', type: 'adjective', tonalityGroup: 'major' },
  { id: 'a-adj-06', label: 'pure', type: 'adjective', tonalityGroup: 'major' },
  { id: 'a-adj-07', label: 'warm', type: 'adjective', tonalityGroup: 'major' },
  { id: 'a-adj-08', label: 'calm', type: 'adjective', tonalityGroup: 'major' },
  { id: 'a-adj-09', label: 'open', type: 'adjective', tonalityGroup: 'major' },
  { id: 'a-adj-10', label: 'serene', type: 'adjective', tonalityGroup: 'major' },
  { id: 'a-adj-11', label: 'distant', type: 'adjective', tonalityGroup: 'major' },
  { id: 'a-adj-12', label: 'golden', type: 'adjective', tonalityGroup: 'major' },
  { id: 'a-adj-25', label: 'tranquil', type: 'adjective', tonalityGroup: 'major' },
  { id: 'a-adj-26', label: 'lucid', type: 'adjective', tonalityGroup: 'major' },
  { id: 'a-adj-27', label: 'fragrant', type: 'adjective', tonalityGroup: 'major' },
  { id: 'a-adj-28', label: 'tender', type: 'adjective', tonalityGroup: 'major' },
  { id: 'a-adj-29', label: 'dewy', type: 'adjective', tonalityGroup: 'major' },
  { id: 'a-adj-30', label: 'radiant', type: 'adjective', tonalityGroup: 'major' },
  { id: 'a-adj-31', label: 'verdant', type: 'adjective', tonalityGroup: 'major' },
  { id: 'a-adj-32', label: 'weightless', type: 'adjective', tonalityGroup: 'major' },
  { id: 'a-adj-33', label: 'sunlit', type: 'adjective', tonalityGroup: 'major' },
  { id: 'a-adj-34', label: 'fresh', type: 'adjective', tonalityGroup: 'major' },
  { id: 'a-adj-35', label: 'luminous', type: 'adjective', tonalityGroup: 'major' },
  { id: 'a-adj-36', label: 'graceful', type: 'adjective', tonalityGroup: 'major' },

  // Adjectives - Minor tonality
  { id: 'a-adj-13', label: 'fading', type: 'adjective', tonalityGroup: 'minor' },
  { id: 'a-adj-14', label: 'pale', type: 'adjective', tonalityGroup: 'minor' },
  { id: 'a-adj-15', label: 'empty', type: 'adjective', tonalityGroup: 'minor' },
  { id: 'a-adj-16', label: 'quiet', type: 'adjective', tonalityGroup: 'minor' },
  { id: 'a-adj-17', label: 'slow', type: 'adjective', tonalityGroup: 'minor' },
  { id: 'a-adj-18', label: 'lonely', type: 'adjective', tonalityGroup: 'minor' },
  { id: 'a-adj-19', label: 'distant', type: 'adjective', tonalityGroup: 'minor' },
  { id: 'a-adj-20', label: 'cold', type: 'adjective', tonalityGroup: 'minor' },
  { id: 'a-adj-21', label: 'grey', type: 'adjective', tonalityGroup: 'minor' },
  { id: 'a-adj-22', label: 'lost', type: 'adjective', tonalityGroup: 'minor' },
  { id: 'a-adj-23', label: 'ancient', type: 'adjective', tonalityGroup: 'minor' },
  { id: 'a-adj-24', label: 'hollow', type: 'adjective', tonalityGroup: 'minor' },
  { id: 'a-adj-37', label: 'wan', type: 'adjective', tonalityGroup: 'minor' },
  { id: 'a-adj-38', label: 'somber', type: 'adjective', tonalityGroup: 'minor' },
  { id: 'a-adj-39', label: 'frail', type: 'adjective', tonalityGroup: 'minor' },
  { id: 'a-adj-40', label: 'silent', type: 'adjective', tonalityGroup: 'minor' },
  { id: 'a-adj-41', label: 'overcast', type: 'adjective', tonalityGroup: 'minor' },
  { id: 'a-adj-42', label: 'fragile', type: 'adjective', tonalityGroup: 'minor' },
  { id: 'a-adj-43', label: 'drowsy', type: 'adjective', tonalityGroup: 'minor' },
  { id: 'a-adj-44', label: 'desolate', type: 'adjective', tonalityGroup: 'minor' },
  { id: 'a-adj-45', label: 'frosted', type: 'adjective', tonalityGroup: 'minor' },
  { id: 'a-adj-46', label: 'veiled', type: 'adjective', tonalityGroup: 'minor' },
  { id: 'a-adj-47', label: 'weathered', type: 'adjective', tonalityGroup: 'minor' },
  { id: 'a-adj-48', label: 'hushed', type: 'adjective', tonalityGroup: 'minor' },

  // Verbs - Major tonality
  { id: 'a-v-01', label: 'float', type: 'verb', tonalityGroup: 'major' },
  { id: 'a-v-02', label: 'drift', type: 'verb', tonalityGroup: 'major' },
  { id: 'a-v-03', label: 'flow', type: 'verb', tonalityGroup: 'major' },
  { id: 'a-v-04', label: 'rise', type: 'verb', tonalityGroup: 'major' },
  { id: 'a-v-05', label: 'shine', type: 'verb', tonalityGroup: 'major' },
  { id: 'a-v-06', label: 'rest', type: 'verb', tonalityGroup: 'major' },
  { id: 'a-v-07', label: 'breathe', type: 'verb', tonalityGroup: 'major' },
  { id: 'a-v-08', label: 'bloom', type: 'verb', tonalityGroup: 'major' },
  { id: 'a-v-09', label: 'glow', type: 'verb', tonalityGroup: 'major' },
  { id: 'a-v-10', label: 'wander', type: 'verb', tonalityGroup: 'major' },
  { id: 'a-v-11', label: 'wake', type: 'verb', tonalityGroup: 'major' },
  { id: 'a-v-12', label: 'settle', type: 'verb', tonalityGroup: 'major' },
  { id: 'a-v-25', label: 'unfold', type: 'verb', tonalityGroup: 'major' },
  { id: 'a-v-26', label: 'shimmer', type: 'verb', tonalityGroup: 'major' },
  { id: 'a-v-27', label: 'sprout', type: 'verb', tonalityGroup: 'major' },
  { id: 'a-v-28', label: 'glisten', type: 'verb', tonalityGroup: 'major' },
  { id: 'a-v-29', label: 'stretch', type: 'verb', tonalityGroup: 'major' },
  { id: 'a-v-30', label: 'hover', type: 'verb', tonalityGroup: 'major' },
  { id: 'a-v-31', label: 'ripple', type: 'verb', tonalityGroup: 'major' },
  { id: 'a-v-32', label: 'open', type: 'verb', tonalityGroup: 'major' },
  { id: 'a-v-33', label: 'sway', type: 'verb', tonalityGroup: 'major' },
  { id: 'a-v-34', label: 'kindle', type: 'verb', tonalityGroup: 'major' },
  { id: 'a-v-35', label: 'listen', type: 'verb', tonalityGroup: 'major' },
  { id: 'a-v-36', label: 'gather', type: 'verb', tonalityGroup: 'major' },

  // Verbs - Minor tonality
  { id: 'a-v-13', label: 'fade', type: 'verb', tonalityGroup: 'minor' },
  { id: 'a-v-14', label: 'fall', type: 'verb', tonalityGroup: 'minor' },
  { id: 'a-v-15', label: 'linger', type: 'verb', tonalityGroup: 'minor' },
  { id: 'a-v-16', label: 'vanish', type: 'verb', tonalityGroup: 'minor' },
  { id: 'a-v-17', label: 'whisper', type: 'verb', tonalityGroup: 'minor' },
  { id: 'a-v-18', label: 'sink', type: 'verb', tonalityGroup: 'minor' },
  { id: 'a-v-19', label: 'wait', type: 'verb', tonalityGroup: 'minor' },
  { id: 'a-v-20', label: 'dissolve', type: 'verb', tonalityGroup: 'minor' },
  { id: 'a-v-21', label: 'forget', type: 'verb', tonalityGroup: 'minor' },
  { id: 'a-v-22', label: 'dream', type: 'verb', tonalityGroup: 'minor' },
  { id: 'a-v-23', label: 'wither', type: 'verb', tonalityGroup: 'minor' },
  { id: 'a-v-24', label: 'sleep', type: 'verb', tonalityGroup: 'minor' },
  { id: 'a-v-37', label: 'tremble', type: 'verb', tonalityGroup: 'minor' },
  { id: 'a-v-38', label: 'dim', type: 'verb', tonalityGroup: 'minor' },
  { id: 'a-v-39', label: 'erode', type: 'verb', tonalityGroup: 'minor' },
  { id: 'a-v-40', label: 'blur', type: 'verb', tonalityGroup: 'minor' },
  { id: 'a-v-41', label: 'brood', type: 'verb', tonalityGroup: 'minor' },
  { id: 'a-v-42', label: 'cool', type: 'verb', tonalityGroup: 'minor' },
  { id: 'a-v-43', label: 'withdraw', type: 'verb', tonalityGroup: 'minor' },
  { id: 'a-v-44', label: 'rustle', type: 'verb', tonalityGroup: 'minor' },
  { id: 'a-v-45', label: 'wane', type: 'verb', tonalityGroup: 'minor' },
  { id: 'a-v-46', label: 'murmur', type: 'verb', tonalityGroup: 'minor' },
  { id: 'a-v-47', label: 'drain', type: 'verb', tonalityGroup: 'minor' },
  { id: 'a-v-48', label: 'slumber', type: 'verb', tonalityGroup: 'minor' },

  // Adverbs - Major tonality
  { id: 'a-adv-01', label: 'softly', type: 'adverb', tonalityGroup: 'major' },
  { id: 'a-adv-02', label: 'gently', type: 'adverb', tonalityGroup: 'major' },
  { id: 'a-adv-03', label: 'peacefully', type: 'adverb', tonalityGroup: 'major' },
  { id: 'a-adv-04', label: 'lightly', type: 'adverb', tonalityGroup: 'major' },
  { id: 'a-adv-05', label: 'freely', type: 'adverb', tonalityGroup: 'major' },
  { id: 'a-adv-06', label: 'warmly', type: 'adverb', tonalityGroup: 'major' },
  { id: 'a-adv-13', label: 'brightly', type: 'adverb', tonalityGroup: 'major' },
  { id: 'a-adv-14', label: 'airily', type: 'adverb', tonalityGroup: 'major' },
  { id: 'a-adv-15', label: 'easily', type: 'adverb', tonalityGroup: 'major' },
  { id: 'a-adv-16', label: 'smoothly', type: 'adverb', tonalityGroup: 'major' },
  { id: 'a-adv-17', label: 'openly', type: 'adverb', tonalityGroup: 'major' },
  { id: 'a-adv-18', label: 'sweetly', type: 'adverb', tonalityGroup: 'major' },

  // Adverbs - Minor tonality
  { id: 'a-adv-07', label: 'slowly', type: 'adverb', tonalityGroup: 'minor' },
  { id: 'a-adv-08', label: 'silently', type: 'adverb', tonalityGroup: 'minor' },
  { id: 'a-adv-09', label: 'dimly', type: 'adverb', tonalityGroup: 'minor' },
  { id: 'a-adv-10', label: 'quietly', type: 'adverb', tonalityGroup: 'minor' },
  { id: 'a-adv-11', label: 'coldly', type: 'adverb', tonalityGroup: 'minor' },
  { id: 'a-adv-12', label: 'darkly', type: 'adverb', tonalityGroup: 'minor' },
  { id: 'a-adv-19', label: 'faintly', type: 'adverb', tonalityGroup: 'minor' },
  { id: 'a-adv-20', label: 'barely', type: 'adverb', tonalityGroup: 'minor' },
  { id: 'a-adv-21', label: 'sadly', type: 'adverb', tonalityGroup: 'minor' },
  { id: 'a-adv-22', label: 'restlessly', type: 'adverb', tonalityGroup: 'minor' },
  { id: 'a-adv-23', label: 'hollowly', type: 'adverb', tonalityGroup: 'minor' },
  { id: 'a-adv-24', label: 'bleakly', type: 'adverb', tonalityGroup: 'minor' },
];
